### PR TITLE
Feature/nid 3

### PR DESCRIPTION
**Pull request by fengshanshan**
- proof chain api
   provide the details of the proof chain in a specific persona

### CODE REVIEW

**Comment by nykma** [comment]
Pretty good! Some improvements:

1. `docs/api.apib` API Doc
2. Please consider this API's use case: The original purpose of this API is to let other user (basiclly `persona` owner) export, backup and validate the whole chain. So, some server-specific params should not be exposed in this API. 
   (e.g. `id` and `previous_id`, since it's strictly bound with server's DB primary key, and has no use during validation procedure)
   Instead, some validation-related params **must** be exposed (e.g. `signature_payload` , `uuid` , etc)
3. The reason why I designed `uuid` param is to make a link "globally unique". "globally" means this link (or more precisely, the whole chain) can be imported into other `proof-server` instance without ambiguous part. 
   So, please imagine a situation that, another user create his/her own `proof-server` instance [1], and he/she want to export his record from our "official" server to his/her own server. Use this situation to challenge your design. 
4. The core, "chain-build" procedure should be made into a separate function under `package model`, since NID-4 will benefit from it too.

**Comment by fengshanshan** [comment]
> Pretty good! Some improvements:
> 
> 1. `docs/api.apib` API Doc
> 2. Please consider this API's use case: The original purpose of this API is to let other user (basiclly `persona` owner) export, backup and validate the whole chain. So, some server-specific params should not be exposed in this API.
>    (e.g. `id` and `previous_id`, since it's strictly bound with server's DB primary key, and has no use during validation procedure)
>    Instead, some validation-related params **must** be exposed (e.g. `signature_payload` , `uuid` , etc)
> 3. The reason why I designed `uuid` param is to make a link "globally unique". "globally" means this link (or more precisely, the whole chain) can be imported into other `proof-server` instance without ambiguous part.
>    So, please imagine a scene that, another user create his/her own `proof-server` instance [1], and he/she want to export some records from our "official" server to his/her own server. Use this scene to challenge your design.
> 4. The core, "chain-build" procedure should be made into a separate function under `package model`, since NID-4 will benefit from it too.
> 
> [1]: We will strongly encourage users doing this in the future.

thanks for suggestion! For those suggestions:
1. add the document for the new proofchain api
2. removed those  server-specific params( `id`,  `previous_id`) and  added the  validation-related params (signature, signature_payload and extra)
3. tidy up the code and put the proof-chain related query process to model layer, let it  be reused by other process.

**Review by nykma — COMMENTED** [review]
Good enough. It's even better if you add another test case to check pagination function.

Create (more than 1 page of) data, and send a page `2` request.

See also: https://github.com/nextdotid/proof-server/blob/develop/controller/proof_query_test.go#L143

**Comment by fengshanshan** [comment]
> Good enough. It's even better if you add another test case to check pagination function.
> 
> Create (more than 1 page of) data, and send a page `2` request.
> 
> See also: https://github.com/nextdotid/proof-server/blob/develop/controller/proof_query_test.go#L143

Thanks for the suggestion! added those test case for pagination

**Review by nykma — APPROVED** [review]
LGTM. Can merge.

**Pull request merged**
